-- XY&Z MUSICAL BINGO HUB
-- Run this entire file in the Supabase SQL editor.

create extension if not exists pgcrypto;

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  venue_slug text not null check (venue_slug ~ '^[a-z0-9-]+$'),
  round_slug text not null check (round_slug ~ '^[a-z0-9-]+$'),
  status text not null default 'active' check (status in ('active', 'ended')),
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

create table if not exists public.tracks (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.sessions(id) on delete cascade,
  position integer not null check (position > 0),
  title text not null,
  artist text not null default '',
  album text not null default '',
  artwork_url text,
  detected_at timestamptz not null default now(),
  unique (session_id, position)
);

create index if not exists sessions_active_venue_idx
  on public.sessions (venue_slug, status, started_at desc);

create index if not exists sessions_active_round_idx
  on public.sessions (venue_slug, round_slug, status, started_at desc);

create index if not exists tracks_session_position_idx
  on public.tracks (session_id, position desc);

alter table public.sessions enable row level security;
alter table public.tracks enable row level security;

-- Guest phones may read active session and song-history information.
drop policy if exists "Public can read sessions" on public.sessions;
create policy "Public can read sessions"
  on public.sessions for select
  to anon, authenticated
  using (true);

drop policy if exists "Public can read tracks" on public.tracks;
create policy "Public can read tracks"
  on public.tracks for select
  to anon, authenticated
  using (true);

-- No public insert/update/delete policies are created.
-- Netlify Functions use the server-only secret key for protected writes.
